"""remove user_id

Revision ID: 068c61bdab0b
Revises: 74d826ffb05b
Create Date: 2021-12-29 14:57:26.990166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068c61bdab0b'
down_revision = '74d826ffb05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('News_user_id_fkey', 'News', type_='foreignkey')
    op.drop_column('News', 'user_id')
    op.drop_constraint('Tags_user_id_fkey', 'Tags', type_='foreignkey')
    op.drop_column('Tags', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tags', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Tags_user_id_fkey', 'Tags', 'Users', ['user_id'], ['id'])
    op.add_column('News', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('News_user_id_fkey', 'News', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###
