"""Add is_super_admin property for User

Revision ID: 11dd6197d33d
Revises: 22dd8249460a
Create Date: 2021-12-27 16:08:24.014407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dd6197d33d'
down_revision = '22dd8249460a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_super_admin')
    # ### end Alembic commands ###
