"""Rename all tables and add deleted_at for Role, User

Revision ID: 25a8061b59e4
Revises: c276d37cc290
Create Date: 2021-12-22 16:50:51.620253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a8061b59e4'
down_revision = 'c276d37cc290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_with_role', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_with_role', 'id')
    # ### end Alembic commands ###
