"""Adding Role Table

Revision ID: 3455f95eef87
Revises: 169f10c04e37
Create Date: 2021-12-21 10:05:08.181238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3455f95eef87'
down_revision = '169f10c04e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'is_super_admin')
    op.drop_column('user', 'created_by')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'updated_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('created_by', sa.TEXT(), server_default=sa.text('CURRENT_USER'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_super_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
