"""Added columns created_at, updated_at for User model

Revision ID: 35812726a1e9
Revises: 18c54d3193d5
Create Date: 2021-12-21 11:44:38.554444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35812726a1e9'
down_revision = '18c54d3193d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('user', sa.Column('updated_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
