"""Added update_role api

Revision ID: 3e77abb83641
Revises: a21de5a50d07
Create Date: 2021-12-23 13:54:20.376011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e77abb83641'
down_revision = 'a21de5a50d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'deleted_at')
    # ### end Alembic commands ###
