"""Added deleted_at for Tags

Revision ID: 46d3d411f796
Revises: 6efdb3eb73fe
Create Date: 2021-12-28 16:37:23.511096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d3d411f796'
down_revision = '6efdb3eb73fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tags', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tags', 'deleted_at')
    # ### end Alembic commands ###
