"""update tinhthanh

Revision ID: 492d32baab36
Revises: 5f23960bb35b
Create Date: 2022-01-10 21:08:42.682325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '492d32baab36'
down_revision = '5f23960bb35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tinhthanh', 'ma',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tinhthanh', 'ten',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tinhthanh', 'tenkhongdau',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tinhthanh', 'ten_tieng_anh',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tinhthanh', 'loai',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tinhthanh', 'quocgia_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('tinhthanh', 'active',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tinhthanh', 'created_at',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tinhthanh', 'created_by',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tinhthanh', 'updated_at',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tinhthanh', 'updated_by',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tinhthanh', 'deleted_at',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tinhthanh', 'deleted_by',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tinhthanh', 'deleted_by',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tinhthanh', 'deleted_at',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tinhthanh', 'updated_by',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tinhthanh', 'updated_at',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tinhthanh', 'created_by',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tinhthanh', 'created_at',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tinhthanh', 'active',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tinhthanh', 'quocgia_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('tinhthanh', 'loai',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tinhthanh', 'ten_tieng_anh',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tinhthanh', 'tenkhongdau',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tinhthanh', 'ten',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tinhthanh', 'ma',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###
