"""update tinhthanh

Revision ID: 5f23960bb35b
Revises: f5dba02ddefe
Create Date: 2022-01-10 21:07:01.165288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f23960bb35b'
down_revision = 'f5dba02ddefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tinhthanh', sa.Column('tenkhongdau', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tinhthanh', 'tenkhongdau')
    # ### end Alembic commands ###
