"""init data

Revision ID: 74d826ffb05b
Revises: 185d3699b152
Create Date: 2021-12-29 14:49:54.878185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d826ffb05b'
down_revision = '185d3699b152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('Tag_News')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tag_News',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Tag_News_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['News.id'], name='Tag_News_news_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['Tags.id'], name='Tag_News_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Tag_News_pkey')
    )
    op.drop_table('Categories')
    # ### end Alembic commands ###
