"""Added created_by field for News, Tag

Revision ID: 85418e72c52f
Revises: 46d3d411f796
Create Date: 2021-12-28 17:15:17.035922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85418e72c52f'
down_revision = '46d3d411f796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('News', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('Tags', sa.Column('created_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tags', 'created_by')
    op.drop_column('News', 'created_by')
    # ### end Alembic commands ###
