"""empty message

Revision ID: 8a96d032cdc3
Revises: 6a1e1ad29538
Create Date: 2021-12-14 16:50:08.192817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a96d032cdc3'
down_revision = '6a1e1ad29538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dateOfBirth', sa.Date(), nullable=False))
    op.add_column('user', sa.Column('address', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('phoneNumber', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phoneNumber')
    op.drop_column('user', 'address')
    op.drop_column('user', 'dateOfBirth')
    # ### end Alembic commands ###
