"""Rename all tables and add deleted_at for Role, User

Revision ID: c276d37cc290
Revises: a2e08965c267
Create Date: 2021-12-22 16:47:42.281495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c276d37cc290'
down_revision = 'a2e08965c267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_with_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_table('UserRole')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserRole',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], name='user_with_role_role_id_fkey1'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='user_with_role_user_id_fkey1'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='user_with_role_pkey1')
    )
    op.drop_table('user_with_role')
    # ### end Alembic commands ###
