"""Update user table

Revision ID: cc1d05b02573
Revises: 8a96d032cdc3
Create Date: 2021-12-14 17:28:50.186820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1d05b02573'
down_revision = '8a96d032cdc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('phoneNumber', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phoneNumber')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
