"""add quanhuyen va xaphuong

Revision ID: cd51f2b1c2b8
Revises: 8533a4e59132
Create Date: 2022-01-10 21:28:24.768388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd51f2b1c2b8'
down_revision = '8533a4e59132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quanhuyen',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('ma', sa.String(length=300), nullable=True),
    sa.Column('ten', sa.String(length=300), nullable=True),
    sa.Column('tenkhongdau', sa.String(length=300), nullable=True),
    sa.Column('ten_tieng_anh', sa.String(length=300), nullable=True),
    sa.Column('loai', sa.String(length=300), nullable=True),
    sa.Column('tinhthanh_id', postgresql.UUID(), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.String(length=300), nullable=True),
    sa.Column('updated_by', sa.String(length=300), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['tinhthanh_id'], ['tinhthanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xaphuong',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('ma', sa.String(length=300), nullable=True),
    sa.Column('ten', sa.String(length=300), nullable=True),
    sa.Column('tenkhongdau', sa.String(length=300), nullable=True),
    sa.Column('ten_tieng_anh', sa.String(length=300), nullable=True),
    sa.Column('loai', sa.String(length=300), nullable=True),
    sa.Column('quanhuyen_id', postgresql.UUID(), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.String(length=300), nullable=True),
    sa.Column('updated_by', sa.String(length=300), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['quanhuyen_id'], ['quanhuyen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xaphuong')
    op.drop_table('quanhuyen')
    # ### end Alembic commands ###
