"""add tinhthanh

Revision ID: e8cb181a6f28
Revises: 492d32baab36
Create Date: 2022-01-10 21:11:08.263372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8cb181a6f28'
down_revision = '492d32baab36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tinhthanh',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('ma', sa.String(length=300), nullable=True),
    sa.Column('ten', sa.String(length=300), nullable=True),
    sa.Column('tenkhongdau', sa.String(length=300), nullable=True),
    sa.Column('ten_tieng_anh', sa.String(length=300), nullable=True),
    sa.Column('loai', sa.String(length=300), nullable=True),
    sa.Column('quocgia_id', postgresql.UUID(), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.String(length=300), nullable=True),
    sa.Column('updated_by', sa.String(length=300), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tinhthanh')
    # ### end Alembic commands ###
