"""Rename all tables and add deleted_at for Role, User

Revision ID: fc6027601db9
Revises: 335024736c8c
Create Date: 2021-12-22 16:52:21.215090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6027601db9'
down_revision = '335024736c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'role_id')
    )
    op.drop_table('user_with_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_with_role',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], name='user_with_role_role_id_fkey1'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='user_with_role_user_id_fkey1'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='user_with_role_pkey1')
    )
    op.drop_table('User_Role')
    # ### end Alembic commands ###
